version: '3'
services:
  nginx:
    image: nginx:1.15.0
    container_name: l3autoseg_nginx
    ports:
      - "8002:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/l3autoseg:/src
      - ./src/l3autoseg/app/static:/static
    depends_on:
      - web
  web:
    build: .
    image: brecheisen/l3autoseg:latest
    container_name: l3autoseg_web
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn server.wsgi -b 0.0.0.0:8001"
    environment:
      - SECRET_KEY=1234
    volumes:
      - ./src/l3autoseg:/src
      - /mnt/localscratch/maastro/Leroy/bodycomposition/logs/gradient_tape/stability_new_params_contour/20210529-084544/saved_models/model_26200:/data/model
      - /mnt/localscratch/maastro/Leroy/bodycomposition/logs/gradient_tape/stability_new_params_contour/20210529-084544/params.json:/data/params.json
      - data:/data
    depends_on:
      - db
  redis:
    restart: always
    image: redis:latest
    container_name: l3autoseg_redis
    command: bash -c "redis-server"
    ports:
      - "6379:6379"
  rq:
#    restart: always
    image: brecheisen/l3autoseg:latest
    container_name: l3autoseg_rq
    command: bash -c "python manage.py rqworker"
    environment:
      - SECRET_KEY=1234
    volumes:
      - /mnt/localscratch/maastro/Leroy/bodycomposition/logs/gradient_tape/stability_new_params_contour/20210529-084544/saved_models/model_26200:/data/model
      - /mnt/localscratch/maastro/Leroy/bodycomposition/logs/gradient_tape/stability_new_params_contour/20210529-084544/params.json:/data/params.json
      - ./src/l3autoseg:/src
      - data:/data
    depends_on:
      - db
      - redis
  db:
    restart: always
    image: postgres:10.5-alpine
    container_name: l3autoseg_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
volumes:
  data:
    driver: local
  postgres_data:
    driver: local
