version: '2'

services:

  db:
    image: postgres:10.5-alpine
    container_name: l3autoseg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"

  nginx:
    restart: always
    build: ./nginx
    container_name: l3autoseg_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    volumes_from:
      - uwsgi
    links:
      - uwsgi
      - db

  uwsgi:
    #restart: always
    build: .
    container_name: l3autoseg_uwsgi
    volumes:
      - ./src/server:/code
      - ./uwsgi.ini:/code/uwsgi.ini
      - ./run_uwsgi.sh:/code/run_uwsgi.sh:ro
      - static_data:/var/www/static
      - image_data:/var/www/images
    links:
      - db

volumes:
  static_data:
    driver: local
  image_data:
    driver: local
  postgres_data:
    driver: local
