# Generated by Django 3.2.3 on 2021-06-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultModel',
        ),
        migrations.RemoveField(
            model_name='datasetmodel',
            name='progress',
        ),
    ]
