# Generated by Django 3.2.3 on 2021-05-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='pred_file_path',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
