# Generated by Django 3.2.3 on 2021-05-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='owner',
        ),
    ]
