# Generated by Django 3.2.3 on 2021-05-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_imagemodel_pred_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='done',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='job_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='job_status',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
