# Generated by Django 3.2.3 on 2021-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0003_auto_20210526_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='png_file_path',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
