# Generated by Django 3.2.3 on 2021-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0004_imagemodel_png_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='png_file_name',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
