# Generated by Django 3.2.3 on 2021-05-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0005_imagemodel_png_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='pred_file_name',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
